module.exports = {
  config: {
    fontSize: 18,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorColor: 'rgba(88,88,88,0.8)',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    borderColor: '#fff',
    showHamburgerMenu: '',
    padding: '12px 14px',
    shell: '',
    shellArgs: ['--login'],
    bell: 'SOUND',
    env: {},
    copyOnSelect: false,
    css: '',
    termCSS: '',
    showWindowControls: '',
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff',
    },
  },
  plugins: [
    'hyperlinks',
    'hyper-papercolor',
  ],
};
