#!/bin/sh

# Ask for root password
sudo -v

# Set macOS defaults
echo "››› set-macOS-defaults"
macOSDefaults.sh

# Install macOS software
echo "››› sudo softwareupdate -i -a"
sudo softwareupdate -i -a

# Install homebrew
if test ! $(which brew)
then
  echo "››› Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew
echo "››› brew update"
brew update

# Upgrade Out-of-date Software
echo "››› brew upgrade"
brew upgrade -all

# Run Homebrew through the Brewfile
echo "››› brew bundle"
brew bundle

echo "››› Installing some brew tools"
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

# Install `wget` with IRI support.
brew install wget --with-iri

# Install more recent versions of some macOS tools.
brew install macvim --HEAD --with-cscope --with-lua --with-override-system-vim --with-luajit --with-python
brew link macvim
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install homebrew/dupes/screen
# brew install homebrew/php/php56 --with-gmp

# Install/Upgrade Oh-My-Zsh
if test $(find $HOME/dotfiles/oh-my-zsh/oh-my-zsh.sh)
then
	echo "››› Upgrading oh-my-zsh"
	sh $ZSH/tools/upgrade.sh
else
	echo "››› Installing oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Install base16-shell
if test $(find $HOME/dotfiles/base16-shell/README.md)
then
	echo "››› Base16-Shell Installed"
else
	echo "››› Installing Base16-Shell"
	git clone https://github.com/chriskempson/base16-shell.git $HOME/dotfiles/base16-shell
fi

# Creating .localrc for personal config
if test ! $(find $HOME/.localrc)
then
	echo "››› Createing .localrc in $HOME/"
	touch $HOME/.localrc
else
	echo "››› File already exists: $HOME/.localrc"
fi

# initDotfiles (must run after oh-my-zsh install)
echo "››› Initializing Dotfiles"
./initDotfiles

# Symlink for GNU core utilities
echo "››› Adding symlink for GNU core utilities"
ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Install Node.js dependencies
echo "››› Installing Node dependencies"
if test ! $(which spoof)
then
  sudo npm install spoof -g
fi

# Install npm@latest
npm i npm@latest -g

# Finish
echo "››› Install Done!"