#!/bin/sh

if [ -e ~/.ssh/id_rsa ]
then
  echo "››› We have a SSH private key! Testing Github connection..."
  ssh -T git@github.com
else
  echo "››› Terminating script: No SSH private key 😝"
  exit 1
fi

# Ask for root password
sudo -v

# Set macOS defaults
echo "››› set-macOS-defaults"
macOSDefaults.sh

# Install macOS software
echo "››› sudo softwareupdate -i -a"
sudo softwareupdate -i -a

# Install homebrew
if test ! $(which brew)
then
  echo "››› Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew
echo "››› brew update"
brew update

# Upgrade Out-of-date Software
echo "››› brew upgrade"
brew upgrade -all

# Run Homebrew through the Brewfile
echo "››› brew bundle"
brew bundle

# Install more recent versions of some macOS tools.
brew install macvim --HEAD --with-cscope --with-lua --with-override-system-vim --with-luajit --with-python
brew link macvim
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install homebrew/dupes/screen
# brew install homebrew/php/php56 --with-gmp

# Install/Upgrade Oh-My-Zsh
if test $(find ~/dotfiles/oh-my-zsh/oh-my-zsh.sh)
then
  echo "››› Oh-My-Zsh exists!"
else
  echo "››› Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Copy nvim files
if [ -e ~/.nvm ]
then
  echo "››› NVM config exists!"
else
  echo "››› Installing NVM!"
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
fi

# Init nvim
if [ -e ~/.vim/pack ]
then
  echo "››› VIM pack exists!"
else
  echo "››› Installing Minpac!"
  mkdir -p ~/.vim/pack/minpac/opt
  cd ~/.vim/pack/minpac/opt
  git clone https://github.com/k-takata/minpac.git
fi

# initDotfiles (must run after oh-my-zsh install)
echo "››› Initializing Dotfiles"
./initDotfiles
source ~/.zshrc

# Copy nvim files
if [ -e ~/.config/nvim ]
then
  echo "››› NeoVim config exists!"
else
  echo "››› NeoVim config copy!"
  cp -r $DOTFILES/nvim ~/.config/
fi

echo "››› Python Installs"
pip2 install --user neovim
pip3 install neovim-remote

echo "››› Ruby Installs"
gem install neovim

echo "››› Install NPM Latest"
npm i npm@latest -g

echo "››› Node Installs"
nvm install node
nvm alias default stable
if test ! $(which spoof)
then
  npm install -g spoof es-ctags
fi

echo "››› Adding symlink for GNU core utilities"
ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

echo "››› Install Done!"
